-- Generated by cross14/staged/prepare_fresh_adapters.py; isolated fresh-play adapter.
-- Selection SHA256: cd2d6c8462f27e8569afdafde94491ed33b1ea988b64aef05b313251ec6042e4
-- Level 7; static modes captured from coin22-v4-l7/selection.json at generation.
-- One immutable policy, continuous play at a speed selected before the match through an entire match.
if train_busy and train_busy() then error('Cannot reload modules during a training match') end
-- The only normal pause is AFTER the final mature match settlement.
if play_busy and play_busy() then error('Cannot reload play controller during a match') end
local Core=assert(loadfile('training/runtime/play_core.lua'))()
local StatusIO=assert(loadfile('training/runtime/status_io.lua'))()
local Recorder=(function()
-- Pure all-frame observer. No MAME, memory, input, file, time or policy APIs.
local Recorder={};Recorder.__index=Recorder
local function copy(v)
 if type(v)~='table' then return v end
 local t={};for k,x in pairs(v) do t[k]=copy(x) end;return t
end
local columns={'frame','round','phase','timer','p1_x','p1_y','p1_hp','p1_displayed_hp','p1_timeout_hp','p1_action','p1_anim','p1_wins','p2_x','p2_y','p2_hp','p2_displayed_hp','p2_timeout_hp','p2_action','p2_anim','p2_wins','preceding_input','preceding_decision','timer_raw','emulated_seconds','issued_input','difficulty_bits','difficulty_mirror','effective_difficulty'}
function Recorder.new()return setmetatable({rows={},decisions={},decision_id=0,last_input='',observed=0},Recorder)end
function Recorder:before(frame,round,phase,s)
 assert(frame==self.observed+1 and frame<=36001,'Full recorder frame sequence/bound')
 local a,b=s.p1,s.p2
 local row={frame,round,phase,s.timer,a.x,a.y,a.hp,a.displayed_hp,a.timeout_hp,a.a,a.anim,a.wins,b.x,b.y,b.hp,b.displayed_hp,b.timeout_hp,b.a,b.anim,b.wins,self.last_input,self.decision_id,s.timer_raw or false,s.emulated_seconds or false,false,s.difficulty_bits,s.difficulty_mirror,s.effective_difficulty}
 self.rows[#self.rows+1]=row;self.row=row;self.observed=frame
end
function Recorder:decision(frame,round,a,b,mode,seq,reason)
 assert(self.decision_id<36001,'Full recorder decision bound')
 self.decision_id=self.decision_id+1
 self.decisions[#self.decisions+1]={id=self.decision_id,frame=frame,round=round,mode=mode,reason=reason or '',sequence=copy(seq),ken=copy(a),cpu=copy(b)}
end
function Recorder:after(effects)
 assert(self.row,'Missing pre-tick observation')
 self.row[25]=effects.input~=nil and effects.input or false
 if effects.input~=nil then self.last_input=effects.input end
end
function Recorder:export()
 return {schema='mame.fighter-frame-trace.v1',columns=columns,rows=self.rows,decisions=self.decisions,observed_frames=self.observed,all_frames=true,all_decisions=true,images={},coverage_note='Every Core tick, including fighting/settling/between. Current snapshots only; no diagnostic images.'}
end
return Recorder

end)()
local function trace_record(r,method,...)
 if r.telemetry_error then return nil end
 local ok,value=pcall(r.recorder[method],r.recorder,...)
 if not ok then r.telemetry_error=tostring(value);return nil end
 return value
end
local m=manager.machine
local active,last
local modes={[0]='c19_ryu_fire_fast',[1]='c22_honda_guarded_descent',[2]='c19_blanka_low_lead_hold',[3]='c19_guile_fire3',[5]='c22_chunli_timeout_guard',[6]='c19_zangief_fire_fast',[7]='c22v4_dhalsim_far_ground_start_guard',[8]='c22v3_bison_ground_throw',[9]='c19_sagat_low_wait',[10]='c19_balrog_sweep95',[11]='c19_vega_low_descent_wait'}
local timeout_guards={[0]=false,[1]=true,[2]=false,[3]=false,[5]=true,[6]=false,[7]=false,[8]=true,[9]=false,[10]=false,[11]=true}
local function readfile(path)
 local f=assert(io.open(path,'rb'));local s=f:read('*a');f:close();return s
end
local function quote(s)
 return '"'..s:gsub('[%z\1-\31\\"]',function(c)
  if c=='"' then return '\\"' elseif c=='\\' then return '\\\\' end
  return string.format('\\u%04x',c:byte())
 end)..'"'
end
local function json(v)
 local t=type(v)
 if t=='nil' then return 'null' elseif t=='boolean' or t=='number' then return tostring(v)
 elseif t=='string' then return quote(v) end
 assert(t=='table','Unsupported JSON type')
 local out={}
 if #v>0 or next(v)==nil then
  for _,x in ipairs(v) do out[#out+1]=json(x) end;return '['..table.concat(out,',')..']'
 end
 for k,x in pairs(v) do out[#out+1]=quote(tostring(k))..':'..json(x) end
 table.sort(out);return '{'..table.concat(out,',')..'}'
end
local function write(path,value)
 local body=json(value)..'\n'
 local f=assert(io.open(path..'.tmp','w'))
 local ok,err=pcall(function() assert(f:write(body)) end)
 local closed,close_err=f:close()
 if not ok then error(err) end
 assert(closed,close_err)
 local ok,err=os.rename(path..'.tmp',path)
 if not ok then
  -- Windows C runtime cannot replace an existing destination. Readers tolerate
  -- the brief missing-file window and incomplete JSON, never replay commands.
  local old=io.open(path,'rb');if not old then error(err) end;old:close()
  assert(os.remove(path));assert(os.rename(path..'.tmp',path))
 end
end
local function snapshot_state()
 local s={timer=0,p1=fighter(0),p2=fighter(1)}
 local raw=mem:read_u8(0xff8ace);local hi,lo=raw>>4,raw&15
 s.timer_raw=raw
 s.timer=(hi<=9 and lo<=9) and hi*10+lo or -1
 for i=0,1 do
  local p=s[i==0 and 'p1' or 'p2'];local base=0xff83c6+i*0x300
  p.wins=mem:read_u8(base+0x290)
  p.displayed_hp=mem:read_i16(base+0x1bc);p.timeout_hp=mem:read_i16(base+0x164)
 end
 s.emulated_seconds=m.time:as_double()
 for k,v in pairs(astra_difficulty.read()) do s[k]=v end
 return s
end
local function view(r)
 return {schema='mame.continuous-play.v1',active=active==r,status=r.status,
  prefix=r.prefix,opponent=r.opponent,mode=r.core.mode,phase=r.core.phase,
  frame=r.core.frame,round=r.core.round,score=r.core.score,timeout_guard=r.core.timeout_guard,
  difficulty_bits=r.difficulty_bits,difficulty_label=astra_difficulty_label,difficulty_checks=r.difficulty_checks,
  effective_difficulty=r.effective_difficulty,effective_difficulty_checks=r.effective_difficulty_checks,
  normal_speed=r.normal_speed,speed=r.speed,pauses_during_match=r.pauses,loads=r.loads,saves=r.saves,
  valid_continuous=r.valid and r.status=='complete',result=r.result,reason=r.reason,
  training_validation=r.training_validation,latest=r.latest,
  diagnostic_level='full',trace_frames=r.recorder.observed,telemetry_error=r.telemetry_error or false,
  evidence_basis='Live current-state observations and native lifecycle audit; no per-round visual-review claim'}
end
local function persist(r)
 if r.published then return end
 local body=json(view(r))..'\n'
 if r.status=='complete' or r.status=='invalid' then
  -- Python polls only this name. It does not exist until the final closed
  -- JSON is renamed into place, and it is never replaced afterwards.
  StatusIO.publish(r.prefix..'-status.json',body)
  r.published=true
 else
  StatusIO.append(r.prefix..'-progress.jsonl',body)
 end
end
local function event(r,e)
 e.frame=r.core.frame;e.emulated_seconds=m.time:as_double()
 r.events[#r.events+1]=e
end
local function finish(result,record)
 local r=record or active;if not r or r.finished then return end
 r.finished=true
 r.result=result.result;r.reason=result.reason;r.valid=r.valid and result.valid==true
 r.status='finishing'
 local function problem(label,err)
  r.valid=false;r.status='invalid'
  local message=label..': '..tostring(err)
  r.reason=r.reason and (r.reason..'; '..message) or message
 end
 local function attempt(label,fn)
  local ok,err=pcall(fn)
  if not ok then problem(label,err) end
  return ok
 end
 -- Clear the lock before our own final pause, but keep this record available
 -- for every error path. No later catch depends on active still being set.
 if active==r then active=nil end
 last=r
 attempt('release inputs',r.release)
 attempt('restore normal speed',normal_speed)
 attempt('pause after match',function() if not m.paused then emu.pause() end end)
 -- Detect edited on-disk policy/controller sources; never hot-reload them mid-match.
 for path,body in pairs(r.sources) do
  local ok,current=pcall(readfile,path)
  if not ok or current~=body then problem('source changed',path) end
 end
 attempt('final screenshot',shot)
 r.status=r.valid and 'complete' or 'invalid'
 local finished_event={kind='match_finished',result=r.result,reason=r.reason,valid=r.valid}
 event(r,finished_event)
 local trace=trace_record(r,'export')
 if r.telemetry_error then problem('full trace incomplete',r.telemetry_error) end
 local function final_log()
  finished_event.valid=r.valid;finished_event.reason=r.reason
  write(r.prefix..'.json',{summary=view(r),rounds=r.core.rounds,events=r.events,settlement_trace=r.settlement_trace,trace=trace,telemetry_error=r.telemetry_error or false})
 end
 -- The terminal status is the commit marker: never publish success before
 -- the final screenshot and complete match log have both succeeded.
 if not attempt('final log',final_log) then attempt('invalid final log',final_log) end
 if not attempt('terminal status',function() persist(r) end) then
  attempt('invalidate final log',final_log)
  attempt('invalid terminal status',function() persist(r) end)
 end
 print('PLAY '..r.status..' '..tostring(r.result or r.reason))
end
local function busy() return active~=nil end
play_busy=busy
function play_status()
 local r=active or last
 if r then persist(r);print(json(view(r))) else print('No continuous match') end
end
function play_abort()
 if active then finish({valid=false,reason='explicit user/controller stop'}) end
end
-- Called by the inbox BEFORE compiling any Lua while playing. No arbitrary commands.
local function request(src)
 local s=src:match('^%s*(.-)%s*$')
 if s=='play_status()' then play_status();return true end
 if s=='play_abort()' or s=='stop()' then play_abort();return true end
 event(active,{kind='request_rejected',request=src})
 return false,'Continuous play is locked: only play_status() or play_abort()/stop() are accepted'
end
play_request=request
local function start_match(prefix,opponent,options)
 assert(not (train_busy and train_busy()),'Training controller busy')
 assert(training_continuous_guard_version==1 and fighter_continuous_guard_version==1
  and play_guarded_bridge_version==1,'Load the guarded control/fighter/bridge modules first')
 assert(not active and not (bot or job or advance or loadwatch or savewatch),'Controller busy')
 assert(m.paused,'Start at a reviewed R1 opening before unpausing')
 assert(m.system.name=='sf2','Expected sf2 World 910522')
 astra_difficulty.check(7-astra_difficulty_bits)
 assert(type(prefix)=='string' and prefix:match('^training/[%w_/%-]+$'),'Use a fresh path under training/')
 for _,suffix in ipairs({'-status.json','-progress.jsonl','.json','-policy.lua','-status.json.tmp','.json.tmp'}) do
  local f=io.open(prefix..suffix,'r');if f then f:close();error('Play prefix already exists') end
 end
 assert(modes[opponent],'Unsupported opponent')
 options=options or {};for k in pairs(options) do assert(k=='training_validation' or k=='speed','Unsupported option: '..tostring(k)) end
 local selected_speed=options.speed or 'normal'
 assert(selected_speed=='normal' or selected_speed=='fast','Speed must be normal or fast')
 local opening=snapshot_state()
 local policy=choose
 local r={prefix=prefix,opponent=opponent,status='running',valid=true,pauses=0,loads=0,saves=0,
  difficulty_bits=astra_difficulty_bits,dip_port_value=m.ioport.ports[':DSWB']:read(),difficulty_checks=0,effective_difficulty=7-astra_difficulty_bits,effective_difficulty_checks=0,
  normal_speed=selected_speed=='normal',speed=selected_speed,events={},settlement_trace={},latest=opening,training_validation=options.training_validation==true,
  policy=policy,fighter=fighter,keys=keys,release=release,sources={},recorder=Recorder.new()}
 local function traced_policy(a,b,selected)
  local seq,reason=policy(a,b,selected)
  trace_record(r,'decision',r.core.frame,r.core.round,a,b,selected,seq,reason)
  return seq,reason
 end
 r.core=Core.new({mode=modes[opponent],opponent=opponent,choose=traced_policy,lead=opponent==8 and 2 or 0,timeout_guard=timeout_guards[opponent]},opening)
 local ok,err=pcall(function()
  for _,path in ipairs({'training/runtime/fighter.lua','training/runtime/play_core.lua','training/runtime/play.lua','training/runtime/status_io.lua','training/runtime/difficulty.lua','training/runtime/settings.lua'}) do
   r.sources[path]=readfile(path)
  end
  local policy_file=assert(io.open(prefix..'-policy.lua','wb'))
  local written,write_err=policy_file:write(r.sources['training/runtime/fighter.lua'])
  local closed,close_err=policy_file:close()
  assert(written,write_err);assert(closed,close_err)
  r.release();normal_speed();m.video.throttled=r.speed=='normal'
  event(r,{kind='match_start',state=opening,mode=r.core.mode,lead_frames=r.core.lead,speed=r.speed})
  active=r;last=r;persist(r);emu.unpause()
  assert(active==r and not r.finished,'Start was interrupted')
 end)
 if not ok then
  finish({valid=false,reason='start failed: '..tostring(err)},r)
  error('Continuous match did not start: '..tostring(err))
 end
end
-- Only the inbox receives the actual start closure, once. An ordinary Lua
-- chunk cannot start a match and then execute a suffix after the lock engages.
local function blocked_start()
 error("Use the bridge's single play_match('training/PREFIX',ID,{training_validation=true|false}) request")
end
play_match=blocked_start
local handed_off=false
function play_take_bridge_handler()
 assert(not handed_off,'Continuous start handler was already handed to the bridge')
 handed_off=true
 play_take_bridge_handler=nil
 return function(prefix,opponent,options)
  assert(play_busy==busy and play_request==request and play_match==blocked_start,
   'Play module changed; reload play.lua and bridge.lua together')
  return start_match(prefix,opponent,options)
 end,busy,request
end
if play_frame_subscription then play_frame_subscription:unsubscribe() end
play_frame_subscription=emu.add_machine_frame_notifier(function()
 if not active then return end
 local r=active
 local ok,err=pcall(function()
  if choose~=r.policy or fighter~=r.fighter or keys~=r.keys or release~=r.release then
   return finish({valid=false,reason='loaded policy or input interface changed'})
  end
  if bot or job or advance or loadwatch or savewatch then return finish({valid=false,reason='foreign controller became active'}) end
  if m.video.throttled~=(r.speed=='normal') or m.video.throttle_rate~=1 then
   r.normal_speed=false;return finish({valid=false,reason='selected game speed changed'})
  end
  r.difficulty_checks=r.difficulty_checks+1
  if m.ioport.ports[':DSWB']:read()~=r.dip_port_value then return finish({valid=false,reason='DIP settings changed during match'}) end
  r.latest=snapshot_state()
  astra_difficulty.check(r.effective_difficulty,r.latest)
  r.effective_difficulty_checks=r.effective_difficulty_checks+1
  if r.core.phase=='settling' or r.latest.timer==0 then
   r.settlement_trace[#r.settlement_trace+1]={frame=r.core.frame+1,round=r.core.round,phase=r.core.phase,state=r.latest}
  end
  trace_record(r,'before',r.core.frame+1,r.core.round,r.core.phase,r.latest)
  local effects=r.core:tick(r.latest)
  trace_record(r,'after',effects)
  if effects.input~=nil then
   r.release()
   for key in effects.input:gmatch('%S+') do
    assert(key~='C' and key~='S' and r.keys[key],'Only ordinary fighting inputs are allowed')
    r.keys[key]:set_value(1)
   end
  end
  for _,e in ipairs(effects.events) do
   event(r,e)
  end
  if effects.terminal then finish(effects.terminal)
  elseif r.core.frame%60==0 or #effects.events>0 then persist(r) end
 end)
 if not ok then finish({valid=false,reason='controller error: '..tostring(err)}) end
end)
if play_pause_subscription then play_pause_subscription:unsubscribe() end
play_pause_subscription=emu.add_machine_pause_notifier(function()
 if active then active.pauses=active.pauses+1;finish({valid=false,reason='native pause during match'}) end
end)
if play_load_subscription then play_load_subscription:unsubscribe() end
play_load_subscription=emu.add_machine_post_load_notifier(function()
 if active then active.loads=active.loads+1;finish({valid=false,reason='native load during match'}) end
end)
if play_save_subscription then play_save_subscription:unsubscribe() end
play_save_subscription=emu.add_machine_pre_save_notifier(function()
 if active then active.saves=active.saves+1;finish({valid=false,reason='native save during match'}) end
end)
if play_reset_subscription then play_reset_subscription:unsubscribe() end
play_reset_subscription=emu.add_machine_reset_notifier(function()
 if active then finish({valid=false,reason='native reset during match'}) end
end)
print('Continuous match controller ready; play_match(prefix,opponent)')
